package: trash
version: '1.0.0-beta'
author: Thomas Skerbis - KLXM Crossmedia
supportpage: https://github.com/KLXM/trash

requires:
    redaxo: '^5.10'
    php:
        version: '>=8.1'
    packages:
        structure: '^2.0.0'

page:
    title: translate:trash
    perm: admin
    icon: rex-icon fa fa-trash
    subpages:
        trash: { title: translate:trash_main }
