package: trash
version: '0.0.1'
author: Thomas Skerbis
supportpage: 

requires:
    redaxo: '^5.10'
    php:
        version: '>=8.1'
    packages:
        structure: '^2.0.0'

page:
    title: translate:trash
    perm: admin
    icon: fa fa-trash
    subpages:
        trash: { title: translate:trash_main }
