package: trash
version: '1.0.1'
author: FriendsOfREDAXO
supportpage: https://github.com/FriendsOfREDAXO/trash/

requires:
    redaxo: '^5.10'
    php:
        version: '>=8.1'
    packages:
        structure: '^2.0.0'

page:
    block: system
    title: translate:trash
    perm: admin
    icon: rex-icon fa fa-trash
    subpages:
        trash: { title: translate:trash_main }
